apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: petclinic-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /api/vet
      - /api/customer
      - /api/visit
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: petclinic
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`petclinic.local`)
      kind: Rule
      services:
        - name: api-gateway
          namespace : spring-petclinic
          port: 80
    - match: (Host(`petclinic.local`) && PathPrefix(`/api/vet`))
      kind: Rule
      services:
        - name: vets-service
          namespace : spring-petclinic
          port: 8080
      middlewares:
        - name: petclinic-stripprefix
    - match: (Host(`petclinic.local`) && PathPrefix(`/api/customer`))
      kind: Rule
      services:
        - name: customers-service
          namespace :  spring-petclinic
          port: 8080
      middlewares:
        - name: petclinic-stripprefix
    - match: (Host(`petclinic.local`) && PathPrefix(`/api/visit`))
      kind: Rule
      services:
        - name: visits-service
          namespace : spring-petclinic
          port: 8080
      middlewares:
        - name: petclinic-stripprefix
